version: "3.8"

services:
  web:
    container_name: web
    build: ./backend
    volumes:
      - ./backend/:/usr/src/backend/
      - .vscode-server/extensions/:/root/.vscode-server/extensions/
      - .vscode-server/extensionsCache/:/root/.vscode-server/extensionsCache/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:15
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=inventory_django
      - POSTGRES_PASSWORD=inventory_django
      - POSTGRES_DB=inventory_django
    ports:
      - 5432:5432

volumes:
  postgres_dev_data:
