# Generated by Django 4.2.6 on 2025-08-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joueurs', to='tournament.equipe'),
        ),
        migrations.AddConstraint(
            model_name='joueur',
            constraint=models.UniqueConstraint(fields=('nom', 'equipe'), name='unique_player_in_team'),
        ),
    ]
