# Generated by Django 4.2.6 on 2025-08-24 11:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_joueur_equipe_joueur_unique_player_in_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_equipe_1', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('score_equipe_2', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('equipe_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_equipe_1', to='tournament.equipe')),
                ('equipe_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchs_equipe_2', to='tournament.equipe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
