# Generated by Django 4.2.6 on 2025-08-24 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='points',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
