# Generated by Django 4.2.6 on 2025-08-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_equipe_points'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(check=models.Q(('score_equipe_1__gte', 0), ('score_equipe_2__gte', 0)), name="scores can't be negative"),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(check=models.Q(('equipe_1', models.F('equipe_2')), _negated=True), name='different_teams'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('equipe_1', 'equipe_2'), name='unique_match'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('equipe_2', 'equipe_1'), name='unique_match_reverse'),
        ),
    ]
