# Generated by Django 4.2.6 on 2025-08-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_match_scores_can_t_be_negative_match_different_teams_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='unique_match_reverse',
        ),
    ]
