# Generated by Django 4.2.6 on 2025-08-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_remove_match_unique_match_reverse'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('equipe_2', 'equipe_1'), name='unique_match_reverse'),
        ),
    ]
