# Generated by Django 4.2.6 on 2025-08-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_match_unique_match_reverse'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='unique_match',
        ),
        migrations.RemoveConstraint(
            model_name='match',
            name='unique_match_reverse',
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('equipe_1', 'equipe_2')},
        ),
    ]
