# Generated by Django 4.2.6 on 2025-08-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_remove_match_unique_match_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('equipe_1', 'equipe_2'), name='unique_match_teams_ordered'),
        ),
    ]
