# Generated by Django 4.2.6 on 2025-08-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_alter_match_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='unique_match_teams_ordered',
        ),
    ]
