# Generated by Django 4.2.6 on 2025-08-24 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_remove_match_unique_match_teams_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='buts_marques',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='equipe',
            name='buts_recus',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
